spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DBNAME}
  cloud:
    stream:
      bindings:
        initiativeQueue-out-0:
          binder: kafka-initiative-outcome
          destination: ${KAFKA_INITIATIVE_OUTCOME_TOPIC:idpay-rule-update}
          content-type: ${KAFKA_CONTENT_TYPE:application/json}
      binders:
        kafka-initiative-outcome:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      configuration:
                        sasl:
                          jaas:
                            config: ${KAFKA_INITIATIVE_SASL_JAAS_CONFIG:}
      function:
        definition: initiativeQueue
      kafka:
        binder:
          configuration:
            session.timeout.ms: '60000'
            sasl:
              mechanism: ${KAFKA_INITIATIVE_SASL_MECHANISM}
              jaas.config: ${KAFKA_INITIATIVE_SASL_JAAS_CONFIG}
            heartbeat.interval.ms: '30000'
            security.protocol: ${KAFKA_INITIATIVE_SECURITY_PROTOCOL}
          consumerProperties:
            socket.connection.setup.timeout:
              ms: '100000'
              max.ms: '200000'
            key:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer
            connections.max.idle.ms: '300000'
            value:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer
          auto-create-topics: 'false'
          brokers: ${KAFKA_BINDER_BROKER_ENDPOINT_LIST}

management:
  endpoints:
    web:
      exposure:
        include: "*"

rest-client:
  backend-io:
    service:
      base-url: ${IO_BACKEND_SERVICE_BASE_URL:}/api/v1
      name: backend-io
      subscriptionKey: ${IO_BACKEND_SERVICE_SUBSCRIPTION_API_KEY:}
      request:
        departmentName: ${IO_BACKEND_SERVICE_DEPARTMENT_NAME:}
        isVisible: ${IO_BACKEND_SERVICE_IS_VISIBLE:false}
feign:
  okhttp:
    enabled: true
  client:
    config:
      backend-io:
        loggerLevel: ${FEIGN_CLIENT_CONFIG_IO_LOG_LEVEL:basic}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    it.gov.pagopa: ${LOG_LEVEL_PAGOPA:INFO}
    it.gov.pagopa.initiative: ${LOG_LEVEL_INITIATIVE:INFO}
    org.springframework.cloud: ${LOG_LEVEL_SPRING_CLOUD:WARN}
    org.springframework.data: ${LOG_LEVEL_SPRING_DATA:INFO}
    org.springframework.boot: ${LOG_LEVEL_SPRING_BOOT:INFO}
    io.swagger: ${LOG_LEVEL_IO_SWAGGER:WARN}
    javax.persistence: ${LOG_LEVEL_JAVAX_PERSISTENCE:INFO}
    org.hibernate: ${LOG_LEVEL_ORG_HIBERNATE:INFO}
    org.mongodb.driver: ${LOG_LEVEL_MONGODB_DRIVER:WARN}

app:
  initiative:
    conditions:
      notifyIO: ${APP_INITIATIVE_CONDITIONS_NOTIFY_IO:true}
      notifyRE: ${APP_INITIATIVE_CONDITIONS_NOTIFY_RE:true}

util:
  crypto:
    aes:
      salt: ${UTIL_CRYPTO_AES_SALT:}
      iv: ${UTIL_CRYPTO_AES_IV:}
      keySize: ${UTIL_CRYPTO_AES_KEY_SIZE:256}
      iterationCount: ${UTIL_CRYPTO_AES_ITERATION_COUNT:10000}
      cipherInstance: AES/GCM/NoPadding
      passphrase: ${UTIL_CRYPTO_AES_PASSPHRASE:}